### ISSUE TITLE
how to change GUC hello_notify.naptime.

### ISSUE THREAD

**Issue by jianhe-fun** [michaelpq/pg_plugins#47] opened 2023-11-07 00:49 UTC
I can use `kill -SIGHUP ` to invoke `hello_notify_sighup`, but hello_notify.nap_time not changed.
can I use sql-callable C function to cause the hello_notify process SIGHUP?
or is there anyway to change the hello_notify.nap_time

**Comment by michaelpq** [comment] 2023-11-16 05:33
Like any custom GUC marked with PGC_SIGHUP, this parameter needs to be updated in a configuration file, then reloaded with SIGHUP. The worker hello_notify invokes ProcessConfigFile(), that should be enough to show the new value. If you cannot change the on-disk configuration, one option is to use ALTER SYSTEM.

Anyway, this is not a bug, so I am closing it.

**Closed by michaelpq** 2023-11-16 05:33 UTC
